### ISSUE TITLE
Effects as functions

### ISSUE THREAD

**Issue by FelipeSG** [Adrianotiger/Neopixel-Effect-Generator#2]
Hello,

I'd like to know if it is possible to turn the effects into functions (like *voids*) and call them whenever I want. 
I'm sorry for the question here but I could not do it by myself.

Thanks in advance.

**Comment by Adrianotiger** [comment]
This is a generator for people who don't know how to programming a led strip or doesn't know how to programming in C++.

There are many factors when you develop a light animation on the strip:
- should it block or should it not block your code (loop)?
- do you want a code that is short but use much RAM or a long code with less RAM?
- do you want other devices too? Like buttons and sensors?

This generator will use less RAM, but will use a lot of flash to program it (I could calculate the RAM in realtime, would be a nice feature).
This will also work together with your sensors, as you just have to call the "strips_loops()" when you have time, inside your loop.

There are many examples with the neopixel library to fade or make a rainbow, they will all idle your loop. This generator use many global variables and has many lines of code (not efficient), but works :)
