### ISSUE TITLE
several sub loops definition issue

### ISSUE THREAD

**Issue by Dgemily** [Adrianotiger/Neopixel-Effect-Generator#6]
thank you for this helpfull tool!

I just found a small issue when creating 2 loops inside a main loop.

loops definition in the generated code are:
`struct Loop strip0loop0(3, false, 1);`
`struct Loop strip0loop00(1, false, 10);`
`struct Loop strip0loop00(2, false, 10);`

I guess it should be like that :
`struct Loop strip0loop0(3, false, 1);`
`struct Loop strip0loop00(1, false, 10);`
`struct Loop strip0loop01(2, false, 10);`

**Comment by Adrianotiger** [comment]
Thank you very much @Dgemily !
It shows that I never tested it with multiple loops inside a loop 😛 
With the last commit, the names should be correct.
Thanks!
