### ISSUE TITLE
Fade blinks between Start and End values

### ISSUE THREAD

**Issue by zibartas** [Adrianotiger/Neopixel-Effect-Generator#9]
It seems that no matter what settings of "Duration", "Delay" and "Every nth LED" I try, I cannot get the code generated by the web UI perform a fade - it just blinks the end-value for a split second on a loop.

**Comment by Adrianotiger** [comment]
Hi Zibartas, can you post the code for this example?

**Comment by Adrianotiger** [comment]
With the last version, it should work. Thank you for the feedback!
